### ISSUE TITLE
java.lang.NoSuchMethodError: 'boolean org.bukkit.inventory.meta.ItemMeta.hasCustomName()'

### ISSUE THREAD

**Issue by nouish** [nouish/EzChestShop#41]
Reported by Santos (santysx) in the EzChestShop Discord: https://mclo.gs/y5xtD9l

```text
[21:49:05 ERROR]: Could not pass event PlayerMoveEvent to EzChestShopReborn v1.8.0
java.lang.NoSuchMethodError: 'boolean org.bukkit.inventory.meta.ItemMeta.hasCustomName()'
        at EzChestShopReborn-1.8.0.jar/me.deadlight.ezchestshop.utils.Utils.getFinalItemName(Utils.java:256) ~[EzChestShopReborn-1.8.0.jar:?]
        at EzChestShopReborn-1.8.0.jar/me.deadlight.ezchestshop.utils.holograms.ShopHologram.<init>(ShopHologram.java:65) ~[EzChestShopReborn-1.8.0.jar:?]
        at EzChestShopReborn-1.8.0.jar/me.deadlight.ezchestshop.utils.holograms.ShopHologram.getHologram(ShopHologram.java:201) ~[EzChestShopReborn-1.8.0.jar:?]
        at EzChestShopReborn-1.8.0.jar/me.deadlight.ezchestshop.listeners.PlayerCloseToChestListener.onMove(PlayerCloseToChestListener.java:129) ~[EzChestShopReborn-1.8.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2065.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-21-cfa3c61]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1562) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:75) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1471) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1478) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1323) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

EzChestShopReborn version:
```text
1.8.0
```

Server Software:
```text
Pufferfish 1.21.1-cfa3c61
```

**Comment by nouish** [comment]
Fixed in bb02cdda3d0db2b000910ded329e3fcb8f4ecfa2.
